module Stig
  module Generators
    module Array
      # Public: Generates an random Array. Elements are generated by a 
      # generator. Size is variable, use a Range with equal start and end for a
      # fixed size.
      #
      # generator - An enumerator or an object responding to #random.
      # size      - A maximum size Integer or Range (default: 1..10).
      #
      # Returns an Array.
      # Raises ArgumentError when an invalid generator was supplied.
      def self.random(generator, size = 1..10)
        unless generator.is_a?(Enumerator) || generator.respond_to?(:random)
          raise ArgumentError, "no #random implemented for #{generator}"
        end

        array = []

        rand(size).times do
          if generator.is_a?(Enumerator)
            element = generator.next
          else
            element = generator.random
          end

          array << element
        end

        array
      end
    end
  end
end
