require "stig/generators/array"
require "stig/generators/character"
require "stig/generators/float"
require "stig/generators/integer"
require "stig/generators/string"
require "stig/generators/symbol"
